# Generated by Django 4.2.23 on 2025-07-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_alter_treatment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='duration',
            field=models.CharField(),
        ),
    ]
