# Generated by Django 4.2.23 on 2025-07-29 23:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_alter_treatment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder-treatment', max_length=255, verbose_name='image'),
        ),
    ]
