# Generated by Django 4.2.23 on 2025-07-30 00:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='nobody', max_length=255, verbose_name='image'),
        ),
    ]
