# Generated by Django 4.2.23 on 2025-07-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_in_touch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
