# Generated by Django 4.2.23 on 2025-07-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_in_touch', '0002_enquiry_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='name_visitor',
            new_name='name',
        ),
    ]
